measurement_comparisons = {
    "metric_weight_comparisons": {
        "1 gram": "About the weight of a paperclip",
        "5 grams": "About the weight of a sheet of paper",
        "10 grams": "Similar to the weight of a standard AA battery",
        "30 grams": "Roughly the weight of a slice of bread",
        "50 grams": "Comparable to a small egg",
        "100 grams": "Similar to a small apple",
        "150 grams": "About the weight of a deck of cards",
        "200 grams": "Comparable to a large potato",
        "250 grams": "Similar to the weight of a baseball",
        "300 grams": "About the weight of a can of soda",
        "500 grams": "Roughly the weight of a loaf of bread",
        "750 grams": "Similar to the weight of a bottle of wine",
        "1 kilogram": "Comparable to a liter of water or a small bag of flour",
        "2 kilograms": "About the weight of a laptop",
        "5 kilograms": "Similar to the weight of a bowling ball"
    },
    "imperial_weight_comparisons": {
        "1 ounce": "About the weight of a slice of bread",
        "3.5 ounces": "Similar to a small apple or a medium-sized dinner roll",
        "7 ounces": "Comparable to a large potato",
        "8.8 ounces": "Similar to the weight of a baseball",
        "10.5 ounces": "About the weight of a can of soda",
        "1 pound": "Roughly the weight of a loaf of bread",
        "1.6 pounds": "Similar to the weight of a bottle of wine",
        "2.2 pounds": "Comparable to a quart of water",
        "4.4 pounds": "About the weight of a laptop",
        "11 pounds": "Similar to the weight of a bowling ball"
    },
    "metric_volume_comparisons": {
        "1 milliliter": "About the size of a small drop of water",
        "5 milliliters": "Roughly the size of a standard dice",
        "15 milliliters": "Comparable to the size of a marble",
        "30 milliliters": "About the size of a shot glass",
        "60 milliliters": "Similar in volume to a large egg",
        "120 milliliters": "Comparable to the volume of a tennis ball",
        "180 milliliters": "Roughly the size of a small orange",
        "240 milliliters": "About the volume of a baseball",
        "500 milliliters": "Similar to the size of a water bottle",
        "1 liter": "Comparable to a quart of milk",
        "2 liters": "About the size of a large soda bottle"
    },
    "imperial_volume_comparisons": {
        "1 teaspoon": "About the size of a small dice",
        "1 tablespoon": "Comparable to the size of a ping-pong ball",
        "1 fluid ounce": "About the size of a shot glass",
        "1/4 cup": "Similar in volume to a large egg",
        "1/2 cup": "Comparable to the volume of a tennis ball",
        "3/4 cup": "Roughly the size of a small orange",
        "1 cup": "About the volume of a baseball",
        "1 pint": "About the size of a large apple",
        "1 quart": "Comparable to a liter bottle of soda"
    },
    "metric_length_comparisons": {
        "1 millimeter": "About the thickness of a credit card",
        "1 centimeter": "Comparable to the width of a pencil eraser",
        "2.5 centimeters": "Roughly the diameter of a quarter",
        "5 centimeters": "Similar in size to a golf ball",
        "10 centimeters": "About the length of a credit card",
        "15 centimeters": "Comparable to the length of a dollar bill",
        "30 centimeters": "About the length of a standard ruler",
        "50 centimeters": "Similar to the length of a medium-sized dog",
        "1 meter": "Roughly the height of a chair seat",
        "2 meters": "Comparable to the height of a door"
    },
    "imperial_length_comparisons": {
        "1 inch": "About the diameter of a quarter",
        "2 inches": "Similar in size to a golf ball",
        "4 inches": "About the length of a credit card",
        "6 inches": "Comparable to the length of a dollar bill",
        "12 inches": "About the length of a standard ruler",
        "20 inches": "Similar to the length of a medium-sized dog",
        "3 feet": "Roughly the height of a chair seat",
        "6 feet": "Comparable to the height of a door"
    },
    "ingredient_comparisons": {
        "1 clove of garlic": "About the size of a fingertip",
        "1 slice of cheese": "Roughly the size of a playing card",
        "1 medium onion": "Similar in size to a baseball",
        "1 medium tomato": "About the size of a tennis ball",
        "1 cup of flour": "Comparable to the size of a grapefruit",
        "1 cup of sugar": "Roughly the volume of a small orange",
        "1 cup of cooked rice": "Fits in a clenched fist",
        "1 tablespoon of butter": "About the size of a standard dice",
        "1 large egg": "Similar in size to a small lemon",
        "1 stick of butter": "Comparable to the size of a small mobile phone"
    },
    "utensil_comparisons": {
        "small plate (6 inches)": "About the size of a dessert plate",
        "medium plate (8 inches)": "Similar to a standard salad plate",
        "large plate (10 inches)": "Comparable to a dinner plate",
        "small bowl (300 milliliters)": "About the size of a cereal bowl",
        "medium bowl (500 milliliters)": "Similar to a soup bowl",
        "large bowl (1 liter)": "Comparable to a serving bowl",
        "small pot (1 liter)": "About the size of a small saucepan",
        "medium pot (2 liters)": "Comparable to a standard saucepan",
        "large pot (4 liters)": "About the size of a Dutch oven",
        "small pan (8 inches)": "Comparable to a small frying pan",
        "medium pan (10 inches)": "Similar to a medium skillet",
        "large pan (12 inches)": "About the size of a large frying pan",
        "baking sheet (9x13 inches)": "Similar to a standard baking tray",
        "baking dish (8x8 inches)": "Comparable to a square casserole dish",
        "large baking dish (9x13 inches)": "Similar to a rectangular lasagna dish"
    }
}
