const prefList = {
	"Cuisines": [
		{ name: "American", imageURL: "" },
		{ name: "British", imageURL: "" },
		{ name: "Brazilian", imageURL: "" },
		{ name: "Caribbean", imageURL: "" },
		{ name: "Chinese", imageURL: "" },
		{ name: "Ethiopian", imageURL: "" },
		{ name: "French", imageURL: "" },
		{ name: "German", imageURL: "" },
		{ name: "Greek", imageURL: "" },
		{ name: "Indian", imageURL: "" },
		{ name: "Italian", imageURL: "" },
		{ name: "Japanese", imageURL: "" },
		{ name: "Korean", imageURL: "" },
		{ name: "Lebanese", imageURL: "" },
		{ name: "Mexican", imageURL: "" },
		{ name: "Moroccan", imageURL: "" },
		{ name: "Spanish", imageURL: "" },
		{ name: "Thai", imageURL: "" },
		{ name: "Turkish", imageURL: "" },
		{ name: "Vietnamese", imageURL: "" },
	],
	"Dietary Preferences": [
		{ name: "Vegetarian", imageURL: "" },
		{ name: "Vegan", imageURL: "" },
		{ name: "Pescatarian", imageURL: "" },
		{ name: "Gluten-Free", imageURL: "" },
		{ name: "Dairy-Free", imageURL: "" },
		{ name: "Halal", imageURL: "" },
		{ name: "Kosher", imageURL: "" },
		{ name: "Low-Carb", imageURL: "" },
		{ name: "Keto", imageURL: "" },
		{ name: "Paleo", imageURL: "" },
		{ name: "Low-Sodium", imageURL: "" },
	],
	"Allergies": [
		{ name: "Milk", imageURL: "" },
		{ name: "Eggs", imageURL: "" },
		{ name: "Fish", imageURL: "" },
		{ name: "Shellfish", imageURL: "" },
		{ name: "Tree Nuts", imageURL: "" },
		{ name: "Peanuts", imageURL: "" },
		{ name: "Wheat", imageURL: "" },
		{ name: "Soy", imageURL: "" },
		{ name: "Sesame", imageURL: "" },
		{ name: "Gluten", imageURL: "" },
		{ name: "Mustard", imageURL: "" },
		{ name: "Sulfites", imageURL: "" },
	],
	"Specific Foods": [
		{ name: "Apples", imageURL: "" },
		{ name: "Bananas", imageURL: "" },
		{ name: "Beef", imageURL: "" },
		{ name: "Bread", imageURL: "" },
		{ name: "Broccoli", imageURL: "" },
		{ name: "Carrots", imageURL: "" },
		{ name: "Cheese", imageURL: "" },
		{ name: "Chicken", imageURL: "" },
		{ name: "Chocolate", imageURL: "" },
		{ name: "Eggs", imageURL: "" },
		{ name: "Garlic", imageURL: "" },
		{ name: "Honey", imageURL: "" },
		{ name: "Lamb", imageURL: "" },
		{ name: "Lentils", imageURL: "" },
		{ name: "Mushrooms", imageURL: "" },
		{ name: "Olive Oil", imageURL: "" },
		{ name: "Onions", imageURL: "" },
		{ name: "Oranges", imageURL: "" },
		{ name: "Pasta", imageURL: "" },
		{ name: "Pork", imageURL: "" },
		{ name: "Potatoes", imageURL: "" },
		{ name: "Rice", imageURL: "" },
		{ name: "Spinach", imageURL: "" },
		{ name: "Strawberries", imageURL: "" },
		{ name: "Tofu", imageURL: "" },
		{ name: "Tomatoes", imageURL: "" },
		{ name: "Yogurt", imageURL: "" },
	],
};
